classifier_paths:
    - "models/rbg/mae_contrast_supcon_model/classifier_s0.pth"
encoder_path: "models/rbg/mae_contrast_supcon_model/encoder.pth"
model_config:
  vit_model:
      hidden_size: 768
      num_hidden_layers: 12
      num_attention_heads: 12
      intermediate_size: 3072
      hidden_act: "gelu"
      hidden_dropout_prob: 0.0
      attention_probs_dropout_prob: 0.0
      initializer_range: 0.02
      layer_norm_eps: 1.e-12
      image_size: 448
      patch_size: 16
      num_channels: 3
      qkv_bias: True
  pool_model:
      dim: 768
      int_dim: 512
      num_heads: 2
  num_classes: 31